In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-01-31 12:11:59.512817: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pramika/miniconda3/envs/rps/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-31 12:11:59.512857: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-31 12:12:01.598612: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pramika/miniconda3/envs/rps/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-31 12:12:01.598640: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-31 12:12:01.598660: I tensorflow/stream_executor/cuda/cuda_diagno

[[9.5491940e-01 1.6850656e-06 6.6953659e-04 4.4409357e-02]]
[[8.9455038e-01 2.8224006e-06 5.6157802e-04 1.0488530e-01]]
[[9.0930265e-01 3.0500648e-06 9.0375188e-04 8.9790620e-02]]
[[9.5025563e-01 2.1401434e-06 9.5040107e-04 4.8791721e-02]]
[[9.1003370e-01 1.5108318e-06 4.5220062e-04 8.9512572e-02]]
[[0.13178134 0.14282325 0.00636977 0.7190257 ]]
[[0.2587919  0.02665408 0.03824904 0.676305  ]]
[[0.1874914  0.00672772 0.03206072 0.77372015]]
[[0.00715817 0.02653288 0.00958439 0.9567246 ]]
[[0.01174413 0.00587989 0.01265269 0.9697233 ]]
[[0.49203673 0.025932   0.08064596 0.4013853 ]]
[[9.7219151e-01 5.8604369e-04 1.0900048e-03 2.6132463e-02]]
[[9.9931026e-01 9.7586653e-06 2.7734353e-04 4.0267897e-04]]
[[9.9678433e-01 6.4742062e-06 2.4407001e-03 7.6861476e-04]]
[[9.8511118e-01 7.0061687e-06 1.3646277e-02 1.2355425e-03]]
[[9.9411786e-01 4.8451302e-06 5.6234035e-03 2.5387428e-04]]
[[9.9490201e-01 3.6807844e-06 9.3680527e-04 4.1574012e-03]]
[[9.75032449e-01 1.05744975e-05 8.46948382e-03 1.648

KeyboardInterrupt: 